name: Codecov via tarpaulin

on:
  push:
    branches: ["main"]
  pull_request:
    # Run on merged pull requests
    types: [ closed ]
  workflow_dispatch:

env:
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        # Docker Hub image
        image: postgres:15.2-alpine
        # Environment variables scoped only for the postgres service container
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run tarpaulin
        run: |
          export JWT_SECRET=secret
          export DATABASE_URL=postgres://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432
          cargo tarpaulin --out Xml -- --test-threads=1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml